Fix dev setup
sdrogers/nplinker pull request #223
Opened 2024-03-12 09:17 UTC by adraismawur

Closes #222 

This fixes some minor issues I had setting up the dev environment on my Linux machine.

Changes:
- Adds sudo to the apt commands used under Linux
- Fixes the version of pytest-fixtures to be <8 to resolve an AttributeError

2024-03-12 12:22 UTC, CunliangGeng commented on bin/install-nplinker-deps
> +            sudo apt update &> /dev/null
```suggestion
            echo "To use 'apt' command, you need to allow 'sudo' by providing password"
            sudo apt update &> /dev/null
```

2024-03-12 12:28 UTC, CunliangGeng commented on requirements.dev.txt
> +pytest<8
lazy fixture is not used in the codebase, so it's better to remove the dependency of `pytest-lazy-fixture` from `requirements.txt`.

2024-03-12 12:29 UTC, CunliangGeng requested changes
Thanks for the update, I left two minor comments.

2024-03-12 12:31 UTC, CunliangGeng commented
The github actions are not passed, which are caused by unit tests (worked well locally), I'll take a look into that.

2024-03-12 15:10 UTC, adraismawur commented on requirements.dev.txt
> +pytest<8
Ok! Done and the pytest dependency is back to latest version.

2024-03-12 15:57 UTC, CunliangGeng approved these changes
Great! It's approved and you can merge it now.

2024-03-13 08:36 UTC, adraismawur commented
Thanks! But it seems I do not have write access to the repository & cannot merge.

2024-03-13 08:45 UTC, CunliangGeng commented
> Thanks! But it seems I do not have write access to the repository & cannot merge.

Aha, I only added you to the org and forgot to give you write access to the repo. Just gave you the access, check please.

2024-03-13 12:22 UTC, merged