Support Bigscape v2 data
sdrogers/nplinker pull request #234
Opened 2024-03-27 11:00 UTC by adraismawur

This PR enables the user to load data from a BiG-SCAPE V2 database file. The `data_sqlite.db` file is expected to be in the same place as the `mix_clustering_[cutoff].tsv` would otherwise be. 

If both files are found, the loader selects the tsv file.

2024-03-27 14:09 UTC, CunliangGeng requested changes
Thanks for adding the support of bigscape v2!

I left some minor comments for you.

One final comment on all files is that please remember to format all files using `ruff`. If you are also using vscode, the formatting could be automatic, see the [guide](https://github.com/NPLinker/nplinker/blob/dev/README.dev.md#linting-and-formatting).

2024-03-27 14:09 UTC, CunliangGeng commented on src/nplinker/arranger.py
> +    database_file = bigscape_dir / "data_sqlite.db"
The name `data_sqlite.db` is pretty generic, and I suggest adding a prefix e.g. `bigscape_data.db`

2024-03-27 14:09 UTC, CunliangGeng commented on src/nplinker/arranger.py
> +    database_file = bigscape_dir / "data_sqlite.db"
Please update the docstrings of methods `validate_bigscape` and `arrange_bigscape` to add the requirements on this database file

2024-03-27 14:09 UTC, CunliangGeng commented on src/nplinker/genomics/bigscape/bigscape_loader_v2.py
> +class BigscapeV2GCFLoader:
Move this class to the file `bigscape_loader.py`?

2024-03-27 14:09 UTC, CunliangGeng commented on src/nplinker/genomics/bigscape/bigscape_loader_v2.py
> +                the filename has a pattern of "data_sqlite.db".
```suggestion
            db_file: Path to the BiG-SCAPE v2 database file,
                the filename has a pattern of "bigscape_data.db".
```

2024-03-27 14:09 UTC, CunliangGeng commented on src/nplinker/genomics/bigscape/bigscape_loader_v2.py
> +        """Get GCF objects from database
```suggestion
        """Get GCF objects from database.
```

2024-03-27 14:09 UTC, CunliangGeng commented on src/nplinker/genomics/bigscape/bigscape_loader_v2.py
> +            cluster_file: path to the BiG-SCAPE database file.
```suggestion
            db_file: path to the BiG-SCAPE database file.
```

2024-03-27 14:09 UTC, CunliangGeng commented on src/nplinker/genomics/bigscape/bigscape_loader_v2.py
> +                the filename has a pattern of "data_sqlite.db".
Is it still necessary to mention the filename pattern?

2024-03-27 14:09 UTC, CunliangGeng commented on src/nplinker/loader.py
> +        # switch depending on found file. prefer V1 if both are found
It's ok to use this logics at the moment. Later it should be adapted e.g. with a new config on bigscape version.

2024-03-27 14:09 UTC, CunliangGeng commented on tests/unit/genomics/test_bigscape_loader_v2.py
> +class TestBigscapelGCFLoader:
Same, move this class to `test_bigscape_loader.py`?

2024-03-27 14:18 UTC, CunliangGeng commented on src/nplinker/genomics/bigscape/bigscape_loader_v2.py
> +            list[GCF]: a list of GCF objects.
```suggestion
            A list of GCF objects.
```

2024-03-27 14:20 UTC, CunliangGeng commented on src/nplinker/genomics/bigscape/bigscape_loader_v2.py
> +            list[GCF]: a list of GCF objects.
The static typing is not needed in docstring and the [API doc](https://nplinker.github.io/nplinker/latest/api/bigscape/) will add it automatically.

2024-03-27 14:20 UTC, CunliangGeng commented on src/nplinker/genomics/bigscape/bigscape_loader_v2.py
> +            list: A list of GCF objects
```suggestion
            A list of GCF objects
```

2024-03-27 15:37 UTC, adraismawur commented on src/nplinker/arranger.py
> +    database_file = bigscape_dir / "data_sqlite.db"
Indeed! This is what the output is named after BiG-SCAPE v2 runs, but we can rename it to something more descriptive.

2024-03-27 16:36 UTC, CunliangGeng commented on src/nplinker/arranger.py
> +    database_file = bigscape_dir / "data_sqlite.db"
Aha, then better to keep the same name in NPLinker, we don't want to bother users to rename it. If bigscape changes this name, then nplinker changes as well.

2024-03-27 16:38 UTC, CunliangGeng commented
Just [merged a PR](https://github.com/NPLinker/nplinker/pull/235) to ignore docstrings for test files. So it's ok to not have docstrings for test functions.

I'm off from now, @gcroci2 could take over this PR.

2024-03-28 10:32 UTC, gcroci2 commented
> Just [merged a PR](https://github.com/NPLinker/nplinker/pull/235) to ignore docstrings for test files. So it's ok to not have docstrings for test functions.
> 
> I'm off from now, @gcroci2 could take over this PR.

Sure! @adraismawur just ask for my review again when you'll have integrated Cunliang's one :)

2024-04-02 11:44 UTC, adraismawur commented
Alright! Changes were committed. Could you review this again?

2024-04-04 07:18 UTC, gcroci2 commented on src/nplinker/loader.py
> +                f"BigSCAPE cluster file {bigscape_cluster_file} or database file {bigscape_db_file} not found."
```suggestion
                f"Neither BigSCAPE cluster file {bigscape_cluster_file} nor database file {bigscape_db_file} were found."
```

2024-04-04 07:22 UTC, gcroci2 requested changes
All good :) Thanks for the contribution!

The action for checking the format needs to pass before merging. Please run ruff as explained [here](https://github.com/NPLinker/nplinker/blob/dev/README.dev.md#linting-and-formatting).

2024-04-04 08:36 UTC, adraismawur commented
Ok I have run the formatter, but there are files outside of those I edited in this PR that fail using ruff.

Should I rebase dev onto this branch and add formatting changes of other files to this one, or should I just merge as-is and the formatting can be done elsewhere?

2024-04-04 09:23 UTC, gcroci2 commented
> Ok I have run the formatter, but there are files outside of those I edited in this PR that fail using ruff.
> 
> Should I rebase dev onto this branch and add formatting changes of other files to this one, or should I just merge as-is and the formatting can be done elsewhere?

I still see:
`src/nplinker/arranger.py:231:101: E501 Line too long (114 > 100)`
Please make sure that the ruff checks pass on the files you edited (only) and then feel free to merge to dev. No worries about other files you didn't touch with this PR. 

About the linting check failing, is this expected? @CunliangGeng If yes, I think we should exclude the checking on such files on the CI, otherwise it can be confusing for contributors.

2024-04-04 09:23 UTC, gcroci2 approved these changes

2024-04-04 11:02 UTC, merged

2024-04-08 13:51 UTC, CunliangGeng commented
@gcroci2 @adraismawur 

> About the linting check failing, is this expected? @CunliangGeng If yes, I think we should exclude the checking on such files on the CI, otherwise it can be confusing for contributors.

Good point! I updated the github actions to only checked changed files in PR #238.