Adding feature: strain mapping locally
sdrogers/nplinker pull request #281
Opened 2024-10-28 15:46 UTC by rtlortega

This is a new feature for generating the file needed for running NPLinker called **strain_mappings in local mode.** 

The src and test were modified in:

- nplinker 
-> antismash_loader.py -> creating a dict for genome --> bgcs
-> strain -> utils.py -> four new functions:
1. extract_strain_metadata (for the creation of the json file)
2. extract features metabolite id -> for making a strain --> features dictionary
3. extract bgcs genome id -> for making a strain --> bgcs dictionary
4. merge features and bgcs
5. build a nice dictionary with the info needed for running NPLinker in local mode

I also added the testing functions:
- test for each function

There is a notebook for running all the functions step by step: ~/nplinker/tests/unit/local_strain_mapping.ipynb
I would strongly suggest that the test/data information is updated with the correct information as antismash results generates. The current strain_mapping is incorrect as well as the folder generated in test/unit/data/antismash. I generated another folder where the data is correct, but I was not sure if adding that to the pull request yet.

2024-10-28 17:43 UTC, justinjjvanderhooft commented
@rtlortega - are the antismash results different due to the use of a different version? I.e., what version did you use for the latest results?

2024-10-29 12:46 UTC, rtlortega commented
I haven't worked with antismash so far, so I can't tell. I didn't use antishmash results, itself, I just re-arranged the naming of the folders as it should be, according to Dora and Annette's knowledge about it. I also know that is wrong because the stain_mappings in the test/data folder is wrong.

2024-10-29 12:52 UTC, justinjjvanderhooft commented
@rtlortega well, it would be "wrong" if is not compatible with the version of antiSMASH used for the current code base of NPLinker, but it wouldn't be "wrong" if a newer version of antiSMASH has a different output than NPLinker expected.

2024-10-30 13:15 UTC, CunliangGeng requested changes
Hi Rosina, thanks for the PR. Before I review the details of the changes, let's first make sure all changes have followed required formats/styles as well as all tests have been added and passed. So, please fix the following issues first:

1. Please update your changes to make sure the code style and static typing are good using the tool `ruff` and `mypy`. See related errors in this check: https://github.com/NPLinker/nplinker/actions/runs/11557614894/job/32277179283?pr=281

2. I did not see any new unit test in the folder `tests/unit` for your new functions/methods. Please add unit tests for your changes, and make sure they have passed before pushing them to the PR.

Regarding your comments:
> I would strongly suggest that the test/data information is updated with the correct information as antismash results generates. The current strain_mapping is incorrect as well as the folder generated in test/unit/data/antismash. I generated another folder where the data is correct, but I was not sure if adding that to the pull request yet.

The data/files in the `tests/unit/data` are independent with each other (as much as possible). So you don't have to care about the relationship between the `antismash` data and the `strain_mappings.json`, they are independent and are used for different unit tests. 
You should add a new folder with new example data to test your new functions. Please remember:  make the example data as simple/small as possible.

2025-01-31 09:53 UTC, closed without merging